[package]
name = "file-structure"
version = "0.0.2"
authors = ["Jo√£o M. Bezerra <marcospb19@hotmail.com>"]
edition = "2018"
description = "Representation of directory/file structure in filesystem, use directly to create, delete or link."
repository = "https://github.com/marcospb19/file-structure"
license = "MIT"

[dependencies]
# libc = "0.2"
